name: qut
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^4.0.0
  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.5
  intl: ^0.16.1
  cached_network_image: ^3.0.0
  flutter_slidable: ^0.5.7
  # flutter_tags: "^0.1.9"
  inview_notifier_list: ^1.0.0
  flutter_tags: "^0.4.9+1"
  # screen_loader: ^2.0.1 #лоадер
  # load: ^1.0.0
  # webview_flutter: ^0.1.1//это просто веб вью
  # url_launcher: ^4.0.2
  video_player: ^2.0.2
  audioplayers: ^0.18.3 #старый плеер, удали потом
  audio_service: ^0.17.0
  just_audio: ^0.7.3
  share: ^2.0.1
  url_launcher: ^6.0.3
  # webview_flutter: ^2.0.2
  # flutter_downloader: ^1.5.2
  # path_provider: any
  # intl: any
  # hive: ^1.4.4+1
  # hive_flutter: ^0.3.1

  app_logger:
    git:
      url: https://github.com/nilinov/app_logger.git
      ref: cbe010397f8b6489e1421eae25236e330c786268

#  app_logger:
#    path: ../../app_logger

dev_dependencies:
  flutter_test:
    sdk: flutter
  # hive_generator: ^0.8.0
  # build_runner: ^1.10.1


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/icons/
    - assets/icons/Feature/
    - assets/images/

    - assets/images/Splash/splash.png

    - assets/icons/threePoint.png
    - assets/icons/Heart_fill.png
    - assets/icons/NO_fill.png
    - assets/icons/favorit_icon.png
    - assets/icons/dissLikeBlackButton.png
    - assets/icons/likeBlackButton.png
    - assets/icons/Close.png

    - assets/icons/VideoPlayer/Fullscreen.png
    - assets/icons/VideoPlayer/Pause_video_Circle.png
    - assets/icons/VideoPlayer/Play_video_Circle.png

    - assets/icons/IconType/audioIcon.png
    - assets/icons/IconType/bookIcon.png
    - assets/icons/IconType/videoIcon.png

    - assets/icons/BBItem/BBItemBook.png
    - assets/icons/BBItem/BBItemAudio.png
    - assets/icons/BBItem/BBItemThreePoint.png
    - assets/icons/BBItem/BBItemBack.png
    - assets/icons/BBItem/BBItemShare.png
    - assets/icons/BBItem/BBItemClose.png
    - assets/icons/BBItem/BBItemFilter.png
    - assets/icons/BBItem/BBItemCloseWhite.png
    - assets/icons/BBItem/BBItemCloseGray.png
    - assets/icons/BBItem/BBItemGears.png


    - assets/icons/CellContent/cellAudioNoSelected.png
    - assets/icons/CellContent/cellVideoNoSelected.png
    - assets/icons/CellContent/cellBookNoSelected.png
    - assets/icons/CellContent/cellAudioSelected.png
    - assets/icons/CellContent/cellVideoSelected.png
    - assets/icons/CellContent/cellBookSelected.png

    - assets/icons/audioPlayer/close.png
    - assets/icons/audioPlayer/pause.png
    - assets/icons/audioPlayer/play.png

    - assets/icons/TabBarIcon/TabBar0.png
    - assets/icons/TabBarIcon/TabBar1.png
    - assets/icons/TabBarIcon/TabBar2.png
    - assets/icons/TabBarIcon/TabBar3.png

    - assets/icons/TabBarIcon/TabBar0_selected.png
    - assets/icons/TabBarIcon/TabBar1_selected.png
    - assets/icons/TabBarIcon/TabBar2_selected.png
    - assets/icons/TabBarIcon/TabBar3_selected.png

    - assets/icons/chekComplain.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
